### ISSUE TITLE
Pass integration tests

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/hermes#149]
To do:

- [x] make sure `skip_on_ci()` also works during integration tests in the sense that those tests should be skipped -> @nikolas-burkoff figured out how to do it, might need action from @dinakar29 automation team
- [x] make sure we have `max.overlaps` argument in `ggrepel` package

![image](https://user-images.githubusercontent.com/15201933/139647059-39f07497-b1af-43b3-9dec-4575b01c0e00.png)
![image](https://user-images.githubusercontent.com/15201933/139647102-03e160b5-2fc4-4553-acca-9747a57b0f81.png)

**Comment by danielinteractive** [comment]
@nikolas-burkoff do you know what is the package version of `ggrepel` that is being used on rocker / BEE images here?

**Comment by nikolas-burkoff** [comment]
I think:

On rocker it's 0.9.1
On BEE it's 0.82

**Comment by danielinteractive** [comment]
ok so then the BEE problem is from this old version.

**Comment by danielinteractive** [comment]
@dinakar29 @nikolas-burkoff I guess we can close this here as nothing to do in `hermes` repo anymore.
