### ISSUE TITLE
`h_get_size_biomart` test error on R 4.1.2

### ISSUE THREAD

**Issue by dinakar29** [insightsengineering/hermes#163]
**Summary**

The following was encountered while running `R CMD check` for hermes v0.99.2.9006, for R 4.1.2 (rocker)

```r
══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test-connections.R:41:3): h_get_annotation_biomart works as expected ──
  `result` not identical to `expected`.
  Component "size": Mean relative difference: 0.005068424
  ── Failure (test-connections.R:84:3): h_get_size_biomart works as expected ─────
  h_get_size_biomart(...) not identical to c(`11185` = 3376L, `10677` = 5889L).
  1/2 mismatches
  [2] 5919 - 5889 == 30
  ── Failure (test-connections.R:92:3): h_get_size_biomart works as expected ─────
  h_get_size_biomart(...) not identical to c(ENSG00000135407 = 5889L, ENSG00000215417 = 3774L).
  1/2 mismatches
  [1] 5919 - 5889 == 30
  
  [ FAIL 3 | WARN 0 | SKIP 16 | PASS 832 ]
  Error: Test failures
  Execution halted
```

System information:

Field | Value
-- | --
Platform | x86_64-pc-linux-gnu (64-bit)
R Version | R version 4.1.2 (2021-11-01)
R Binary | /usr/local/bin/R
Rscript Binary | /usr/local/bin/Rscript
R Libraries | /opt/rlibs/nest_release/libs, /opt/rlibs/nest_release/libs
Start Timestamp | Mon 17 Jan 2022 05:21:52 PM UTC
End Timestamp | Mon 17 Jan 2022 06:31:04 PM UTC

**Comment by arkadiuszbeer** [comment]
Same error on bee@4.0.3

**Comment by danielinteractive** [comment]
@arkadiuszbeer yes, this has nothing to do with R version actually as mentioned on chat. the fix fixes it
