### ISSUE TITLE
remove outdated long file name vdiffr files from snapshots

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/hermes#195]
To do:

- [x] Go through https://github.com/insightsengineering/hermes/tree/main/tests/testthat/_snaps and remove `*new.svg` files
- [x] Add a pattern to `.gitignore` to avoid committing those in the future
- [x] rerun the tests and accept new snapshots
- [ ] make sure tests pass

Background:

When doing R CMD CHECK on one of our internal systems I got following NOTE. Please double check if this is fixable and if yes - make appropriate changes.

```
* checking for portable file names ... NOTE
Found the following non-portable file path:
  hermes/tests/testthat/_snaps/differential/autoplot-for-hermesdatadiffexpr-with-custom-options.new.svg

Tarballs are only required to store paths of up to 100 bytes and cannot
store those of more than 256 bytes, with restrictions including to 100
bytes for the final component.
See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
```

**Comment by BFalquet** [comment]
add to gitignore:

```
# Ignore new debug snapshots
*_.new.svg
*_.new.png
```
