### ISSUE TITLE
Warning about the deprecated syntax `..count..` 

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/hermes#206]
To do:

- [x] Migrate to new `ggplot2` syntax to avoid warning about the deprecated syntax `..count..` 
	- [x] see https://github.com/insightsengineering/hermes/blob/fc3dfbaff8adc5948b59f618c6552cb6d575d769/R/graphs.R#L31
	- [x] add a corresponding test
	- [x] add a NEWS entry

**Comment by moronip81** [comment]
error popped up in https://insightsengineering.github.io/biomarker-catalog/graphs/rnag01.html
proposed implementation in https://github.com/insightsengineering/hermes/commit/1fbf708163ce9e80e2efaa19ecc49e8532c0a0da
